[package]
name = "reskyadhyaksa/untitled-project"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@^1.4.0"
Promise = "evaera/promise@^4.0.0"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Reflex = "littensy/reflex@^4.3.1"
React = "jsdotlua/react@^17.1.0"
ReactRoblox = "jsdotlua/react-roblox@^17.1.0"
ReactReflex = "littensy/react-reflex@^0.3.4"
Spring = "sleitnick/spring@1.0.0"
Signal = "sleitnick/signal@^2.0.1"
Blink = "devlsayed/blink@0.18.6"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"